### ISSUE TITLE
waffle.io / something on the likes?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.github#1]
@jensens not sure if tangential or not, but I understood from discussions during PLOG 2015 that we will look for a solution to orchestrate issues/pull requests in an overview/kanban/scrum like thingie. i.e waffle.io or other tools like that.

@polyester any progress on this?

**Comment by jensens** [comment]
this is about cleanup and collecting of tools to deal with simple tasks like having unique language for labels, not about working actually with the issues. this is better done in some webapp. i also stumbled over https://huboard.com/ - no idea if this works for us, just as an addition.

we may want to move some of the statistics code of ploneorg.core also over to here, it has many similarities. but well, thats not the point at the moment.

**Comment by jensens** [comment]
~~After a quick look https://waffle.io/ is management per repository (afaict). Not what we need imo! We need some tool to manage all repositories in `plone` organization.~~

```
Multiple Repos on a Single Board

Connect any number of GitHub repositories to a single board. 
View all of your open issues and pull requests for a single project, 
multiple projects, or across your entire organization.
```

**Comment by jensens** [comment]
https://waffle.io/plone/products.cmfplone

after i now had a quick look at waffle.io some questions raised
- Q: do we have a common workflow for issues? 
- Q: do we want to introduce one? 
- Q: who is champion to supervise and ensure the process is used by all collaborators?
- Con: all the cards are using much space, so its difficult to get an good overview. github api with its filters is much better here.
- Pro: We have a tool to manage (or all relevant) core repositories at once.
- Pro: Columns are just labels on the issue.
- Q, Con: If a label is removed at gihub this is not reflected immediatly at waffle. - we need to check the sync.
- Q: figure out how we can handle the PLIP process together with normal issues process and PR process
  ....

**Comment by loechel** [comment]
is this still a point, as github projects also have a kanban board?

**Comment by svx** [comment]
@loechel 

Maybe I am wrong, but was not the idea to have ONE board, the GitHub kanban thinngie is only per repo afaik.

**Comment by loechel** [comment]
@svx AFAIK the github project board could also be applied for an organisation and therefore cross repos. Look at https://github.com/orgs/plone/projects

**Comment by jensens** [comment]
imo there is no need for waffle anymore. the organisation wide boards are good enough.

**Comment by loechel** [comment]
@jensens & @svx so could we close this issue?
